config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get "search" => "companies#search"
  resources :messages
  resources :message_templates, only: [:show]
  resource :session
  # delete '/logout', to: 'sessions#destroy'
  resources :passwords, param: :token
  draw :madmin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "messages#index"
end

app/models/company.rb
class Company < ApplicationRecord
  scope :search, ->(query) {
    where("name LIKE ?", "%#{query}%") # Still safe due to parameterized query
  }

  enum :status, { draft: 0, published: 1, archived: 2, trashed: 3 }

  validates :name, presence: true


  def to_combobox_display
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: [:index]

  # GET /companies or /companies.json
  def search
    
  end

  def index
    # @companies = Company.published.limit(10)
    @companies = Company.search params[:q]
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy!

    respond_to do |format|
      format.html { redirect_to companies_path, status: :see_other, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.expect(company: [ :name, :website_url ])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p><%= link_to company.name, company_path(company) %></p>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :website_url, style: "display: block" %>
    <%= form.text_field :website_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% content_for :title, "Editing company" %>

<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Companies" %>

<h1>Companies</h1>

<%= form_with url: search_url do |form| %>
  <%= form.combobox :search, companies_path, name_when_new: "user[favorite_movie_attributes][name]" %>
<% end %>


<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/index.turbo_stream.erb
<%= async_combobox_options @companies %>

app/views/companies/new.html.erb
<% content_for :title, "New company" %>

<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>