config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get "search" => "companies#search"
  resources :messages
  resources :message_templates, only: [:show]
  resource :session
  # delete '/logout', to: 'sessions#destroy'
  resources :passwords, param: :token
  draw :madmin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "messages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Madmin Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if Current.user.present? %>
      <%= Current.user.email_address %>  <%= link_to 'Go to Madmin Dashboard', '/madmin' %> 
      <%= link_to 'Companies', companies_path %> 
      <%= link_to 'Log out', session_path, method: :delete, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to 'Companies', companies_path %> 
      <%= link_to 'Log in', new_session_path %> 
    <% end %>
    
    <%= yield %>
  </body>
</html>